speed(0)
penup()
setposition(-25, -200)
def square_circle_stack():
    pendown()
    for i in range(4):
        forward(50)
        left(90)
    penup()
    left(90)
    forward(50)
    right(90)
    forward(25)
    pendown()
    circle(25)
    penup()
    backward(25)
    left(90)
    forward(50)
    right(90)
for i in range(4):
    square_circle_stack()